services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - QTT_LOG_DIR=/var/log/qtt
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/api/status').read(); sys.exit(0)"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - api
    ports:
      - "5173:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
